// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/registerConfiguration.proto

package registerConfiguration

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RegisterConfiguration service

func NewRegisterConfigurationEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RegisterConfiguration service

type RegisterConfigurationService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (RegisterConfiguration_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (RegisterConfiguration_PingPongService, error)
}

type registerConfigurationService struct {
	c    client.Client
	name string
}

func NewRegisterConfigurationService(name string, c client.Client) RegisterConfigurationService {
	return &registerConfigurationService{
		c:    c,
		name: name,
	}
}

func (c *registerConfigurationService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "RegisterConfiguration.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerConfigurationService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (RegisterConfiguration_StreamService, error) {
	req := c.c.NewRequest(c.name, "RegisterConfiguration.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &registerConfigurationServiceStream{stream}, nil
}

type RegisterConfiguration_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type registerConfigurationServiceStream struct {
	stream client.Stream
}

func (x *registerConfigurationServiceStream) Close() error {
	return x.stream.Close()
}

func (x *registerConfigurationServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *registerConfigurationServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *registerConfigurationServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *registerConfigurationServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registerConfigurationService) PingPong(ctx context.Context, opts ...client.CallOption) (RegisterConfiguration_PingPongService, error) {
	req := c.c.NewRequest(c.name, "RegisterConfiguration.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &registerConfigurationServicePingPong{stream}, nil
}

type RegisterConfiguration_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type registerConfigurationServicePingPong struct {
	stream client.Stream
}

func (x *registerConfigurationServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *registerConfigurationServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *registerConfigurationServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *registerConfigurationServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *registerConfigurationServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *registerConfigurationServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RegisterConfiguration service

type RegisterConfigurationHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, RegisterConfiguration_StreamStream) error
	PingPong(context.Context, RegisterConfiguration_PingPongStream) error
}

func RegisterRegisterConfigurationHandler(s server.Server, hdlr RegisterConfigurationHandler, opts ...server.HandlerOption) error {
	type registerConfiguration interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type RegisterConfiguration struct {
		registerConfiguration
	}
	h := &registerConfigurationHandler{hdlr}
	return s.Handle(s.NewHandler(&RegisterConfiguration{h}, opts...))
}

type registerConfigurationHandler struct {
	RegisterConfigurationHandler
}

func (h *registerConfigurationHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.RegisterConfigurationHandler.Call(ctx, in, out)
}

func (h *registerConfigurationHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.RegisterConfigurationHandler.Stream(ctx, m, &registerConfigurationStreamStream{stream})
}

type RegisterConfiguration_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type registerConfigurationStreamStream struct {
	stream server.Stream
}

func (x *registerConfigurationStreamStream) Close() error {
	return x.stream.Close()
}

func (x *registerConfigurationStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *registerConfigurationStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *registerConfigurationStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *registerConfigurationStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *registerConfigurationHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.RegisterConfigurationHandler.PingPong(ctx, &registerConfigurationPingPongStream{stream})
}

type RegisterConfiguration_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type registerConfigurationPingPongStream struct {
	stream server.Stream
}

func (x *registerConfigurationPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *registerConfigurationPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *registerConfigurationPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *registerConfigurationPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *registerConfigurationPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *registerConfigurationPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
